import { PaletteData } from '@/lib/types/palette';
import { paletteToDTCG } from '@/lib/figma/dtcg';

export type ExportFormat =
  | 'json'
  | 'dtcg'
  | 'tokensStudio'
  | 'css'
  | 'scss'
  | 'mui'
  | 'tailwind'
  | 'mcpPrompt';

export const FORMAT_LABELS: Record<ExportFormat, string> = {
  json: 'JSON (Native)',
  dtcg: 'DTCG',
  tokensStudio: 'Tokens Studio',
  css: 'CSS Variables',
  scss: 'SCSS Variables',
  mui: 'MUI Theme (TS)',
  tailwind: 'Tailwind Config',
  mcpPrompt: 'Claude MCP Prompt',
};

export const FORMAT_EXTENSIONS: Record<ExportFormat, string> = {
  json: 'json',
  dtcg: 'json',
  tokensStudio: 'json',
  css: 'css',
  scss: 'scss',
  mui: 'ts',
  tailwind: 'js',
  mcpPrompt: 'md',
};

// ── Helpers ──

const kebab = (s: string) => s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

const forEachAction = (
  data: PaletteData,
  cb: (name: string, mode: 'light' | 'dark', shade: string, value: string) => void
) => {
  (data.palette ?? []).forEach(entry => {
    const [name, palette] = Object.entries(entry)[0] ?? [];
    if (!name || !palette) return;
    (['light', 'dark'] as const).forEach(mode => {
      Object.entries(palette[mode]).forEach(([shade, value]) => {
        cb(name, mode, shade, value);
      });
    });
  });
};

// ── Native JSON ──

export function toJSON(data: PaletteData): string {
  return JSON.stringify(data, null, 2);
}

// ── DTCG ──

export function toDTCG(data: PaletteData): string {
  return JSON.stringify(paletteToDTCG(data), null, 2);
}

// ── Tokens Studio (Figma plugin format) ──

export function toTokensStudio(data: PaletteData): string {
  const global: Record<string, Record<string, Record<string, unknown>>> = { color: {} };

  forEachAction(data, (name, mode, shade, value) => {
    if (!global.color[name]) global.color[name] = {};
    if (!global.color[name][mode]) global.color[name][mode] = {};
    (global.color[name][mode] as Record<string, unknown>)[shade] = {
      value,
      type: 'color',
    };
  });

  // Grey
  if (data.themeTokens?.grey) {
    global.color.grey = {};
    (['light', 'dark'] as const).forEach(mode => {
      (global.color.grey as Record<string, unknown>)[mode] = Object.fromEntries(
        Object.entries(data.themeTokens!.grey[mode]).map(([k, v]) => [
          k,
          { value: v, type: 'color' },
        ])
      );
    });
  }

  // Utility
  if (data.themeTokens?.utility) {
    (['light', 'dark'] as const).forEach(mode => {
      Object.entries(data.themeTokens!.utility[mode]).forEach(([groupName, entries]) => {
        if (!global.color[groupName]) global.color[groupName] = {};
        (global.color[groupName] as Record<string, unknown>)[mode] = Object.fromEntries(
          Object.entries(entries).map(([k, v]) => [k, { value: v, type: 'color' }])
        );
      });
    });
  }

  return JSON.stringify({ global }, null, 2);
}

// ── CSS Variables ──

export function toCSS(data: PaletteData): string {
  const lightVars: string[] = [];
  const darkVars: string[] = [];

  forEachAction(data, (name, mode, shade, value) => {
    const varName = `--color-${kebab(name)}-${kebab(shade)}`;
    (mode === 'light' ? lightVars : darkVars).push(`  ${varName}: ${value};`);
  });

  if (data.themeTokens?.grey) {
    Object.entries(data.themeTokens.grey.light).forEach(([k, v]) =>
      lightVars.push(`  --color-grey-${k}: ${v};`)
    );
    Object.entries(data.themeTokens.grey.dark).forEach(([k, v]) =>
      darkVars.push(`  --color-grey-${k}: ${v};`)
    );
  }

  if (data.themeTokens?.utility) {
    (['light', 'dark'] as const).forEach(mode => {
      const target = mode === 'light' ? lightVars : darkVars;
      Object.entries(data.themeTokens!.utility[mode]).forEach(([group, entries]) => {
        Object.entries(entries).forEach(([key, value]) => {
          target.push(`  --color-${kebab(group)}-${kebab(key)}: ${value};`);
        });
      });
    });
  }

  return `:root {\n${lightVars.join('\n')}\n}\n\n[data-theme="dark"] {\n${darkVars.join('\n')}\n}\n`;
}

// ── SCSS Variables ──

export function toSCSS(data: PaletteData): string {
  const lines: string[] = ['// Generated by Palette Pally\n'];

  forEachAction(data, (name, mode, shade, value) => {
    lines.push(`$color-${kebab(name)}-${kebab(shade)}-${mode}: ${value};`);
  });

  if (data.themeTokens?.grey) {
    lines.push('\n// Grey');
    (['light', 'dark'] as const).forEach(mode => {
      Object.entries(data.themeTokens!.grey[mode]).forEach(([k, v]) =>
        lines.push(`$color-grey-${k}-${mode}: ${v};`)
      );
    });
  }

  if (data.themeTokens?.utility) {
    lines.push('\n// Utility');
    (['light', 'dark'] as const).forEach(mode => {
      Object.entries(data.themeTokens!.utility[mode]).forEach(([group, entries]) => {
        Object.entries(entries).forEach(([key, value]) => {
          lines.push(`$color-${kebab(group)}-${kebab(key)}-${mode}: ${value};`);
        });
      });
    });
  }

  return lines.join('\n') + '\n';
}

// ── MUI Theme (TypeScript) ──

const SEMANTIC_NAMES = ['primary', 'secondary', 'success', 'warning', 'info', 'error'];

export function toMuiTheme(data: PaletteData): string {
  const findVariant = (name: string, mode: 'light' | 'dark') => {
    const idx = data.names?.findIndex(n => n.toLowerCase() === name);
    if (idx === undefined || idx < 0) return null;
    const entry = data.palette?.[idx];
    if (!entry) return null;
    return Object.values(entry)[0]?.[mode] ?? null;
  };

  const buildPalette = (mode: 'light' | 'dark'): string => {
    const entries: string[] = [`    mode: '${mode}',`];

    SEMANTIC_NAMES.forEach(name => {
      const v = findVariant(name, mode);
      if (!v) return;
      entries.push(
        `    ${name}: {`,
        `      main: '${v.main}',`,
        `      dark: '${v.dark}',`,
        `      light: '${v.light}',`,
        `      contrastText: '${v.contrastText}',`,
        `    },`
      );
    });

    if (data.themeTokens?.grey?.[mode]) {
      entries.push('    grey: {');
      Object.entries(data.themeTokens.grey[mode]).forEach(([k, v]) =>
        entries.push(`      ${k}: '${v}',`)
      );
      entries.push('    },');
    }

    const u = data.themeTokens?.utility?.[mode];
    if (u?.text) {
      entries.push('    text: {');
      Object.entries(u.text).forEach(([k, v]) => entries.push(`      ${k}: '${v}',`));
      entries.push('    },');
    }
    if (u?.background) {
      entries.push('    background: {');
      Object.entries(u.background).forEach(([k, v]) => entries.push(`      ${k}: '${v}',`));
      entries.push('    },');
    }
    if (u?.divider?.default) {
      entries.push(`    divider: '${u.divider.default}',`);
    }

    return entries.join('\n');
  };

  return `import { createTheme } from '@mui/material/styles';

// Light theme
export const lightTheme = createTheme({
  palette: {
${buildPalette('light')}
  },
});

// Dark theme
export const darkTheme = createTheme({
  palette: {
${buildPalette('dark')}
  },
});
`;
}

// ── Tailwind Config ──

export function toTailwind(data: PaletteData): string {
  const colors: Record<string, Record<string, string> | string> = {};

  (data.palette ?? []).forEach(entry => {
    const [name, palette] = Object.entries(entry)[0] ?? [];
    if (!name || !palette) return;
    colors[name] = {
      DEFAULT: palette.light.main,
      light: palette.light.light,
      dark: palette.light.dark,
      lighter: palette.light.lighter,
      contrast: palette.light.contrastText,
    };
  });

  if (data.themeTokens?.grey) {
    const greyMap: Record<string, string> = {};
    Object.entries(data.themeTokens.grey.light).forEach(([k, v]) => {
      greyMap[k] = v;
    });
    colors.grey = greyMap;
  }

  return `/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: ${JSON.stringify(colors, null, 8).replace(/^/gm, '      ').trim()},
    },
  },
};
`;
}

// ── Claude MCP Prompt (for Claude Desktop with Figma MCP) ──

export function toMCPPrompt(data: PaletteData): string {
  const dtcgJson = JSON.stringify(paletteToDTCG(data), null, 2);
  const primaryColor = data.colors?.[0] ?? 'N/A';
  const colorCount = data.palette?.length ?? 0;

  return `# Palette Pally → Figma Variables (via MCP)

以下のカラーパレットを Figma ファイルの Variable Collection として作成してください。

## パレット概要
- **Primary**: ${primaryColor}
- **Action Colors**: ${colorCount} 色
- **Theme Tokens**: Grey scale + Utility tokens (text/background/surface/action/divider/common)
- **Modes**: light, dark

## 指示
1. Figma MCP を使用して、以下の DTCG 形式のトークンを Variable Collection として作成
2. 各 Collection で "light" と "dark" の 2 モードを設定
3. Variable 名は DTCG のパスを "/" 区切りで使用 (例: \`primary/main\`)

## DTCG トークンデータ

\`\`\`json
${dtcgJson}
\`\`\`

## 期待する結果
- Collection: \`action-colors\`, \`grey\`, \`utility\` が作成される
- 各 Collection に light / dark モードの値が設定される
- Figma での Variable 名の一覧を返してください
`;
}

// ── Registry ──

export const FORMATTERS: Record<ExportFormat, (data: PaletteData) => string> = {
  json: toJSON,
  dtcg: toDTCG,
  tokensStudio: toTokensStudio,
  css: toCSS,
  scss: toSCSS,
  mui: toMuiTheme,
  tailwind: toTailwind,
  mcpPrompt: toMCPPrompt,
};

// ── Import detection ──

export type ImportResult =
  | { format: 'json'; data: PaletteData }
  | { format: 'dtcg'; data: Partial<PaletteData> }
  | { format: 'tokensStudio'; data: Partial<PaletteData> }
  | { format: 'unknown'; error: string };

export function detectAndParse(text: string): ImportResult {
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    return { format: 'unknown', error: 'Invalid JSON' };
  }

  if (typeof parsed !== 'object' || parsed === null) {
    return { format: 'unknown', error: 'Not a JSON object' };
  }

  const obj = parsed as Record<string, unknown>;

  // Native JSON: has colors/names/palette
  if (Array.isArray(obj.colors) && Array.isArray(obj.names) && Array.isArray(obj.palette)) {
    return { format: 'json', data: parsed as PaletteData };
  }

  // Tokens Studio: has global.color
  if (obj.global && typeof obj.global === 'object' && 'color' in (obj.global as object)) {
    return {
      format: 'tokensStudio',
      data: parseTokensStudio(obj.global as Record<string, unknown>),
    };
  }

  // DTCG: has action-colors or grey with $value
  if ('action-colors' in obj || 'grey' in obj || 'utility' in obj) {
    return { format: 'dtcg', data: { colors: [], names: [], palette: [], themeTokens: null, numColors: 0 } };
  }

  return { format: 'unknown', error: 'Unrecognized format' };
}

function parseTokensStudio(global: Record<string, unknown>): Partial<PaletteData> {
  const color = (global.color ?? {}) as Record<string, unknown>;
  const colors: string[] = [];
  const names: string[] = [];

  for (const [groupName, group] of Object.entries(color)) {
    if (typeof group !== 'object' || group === null) continue;
    const light = (group as Record<string, unknown>).light;
    if (light && typeof light === 'object') {
      const main = (light as Record<string, { value?: string }>).main;
      if (main?.value) {
        colors.push(main.value);
        names.push(groupName);
      }
    }
  }

  return { colors, names, numColors: colors.length };
}
